/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables;


import com.rocketmart.jooq.Indexes;
import com.rocketmart.jooq.Keys;
import com.rocketmart.jooq.Rocketmart;
import com.rocketmart.jooq.tables.records.TbAdminContactRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 관리자 문의
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbAdminContact extends TableImpl<TbAdminContactRecord> {

    private static final long serialVersionUID = 1468917137;

    /**
     * The reference instance of <code>rocketmart.TB_ADMIN_CONTACT</code>
     */
    public static final TbAdminContact TB_ADMIN_CONTACT = new TbAdminContact();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbAdminContactRecord> getRecordType() {
        return TbAdminContactRecord.class;
    }

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.CONTACT_SEQ</code>. 컨택 일련번호
     */
    public final TableField<TbAdminContactRecord, Integer> CONTACT_SEQ = createField(DSL.name("CONTACT_SEQ"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "컨택 일련번호");

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.USR_NM</code>. 문의자명
     */
    public final TableField<TbAdminContactRecord, String> USR_NM = createField(DSL.name("USR_NM"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "문의자명");

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.EMAIL</code>. email
     */
    public final TableField<TbAdminContactRecord, String> EMAIL = createField(DSL.name("EMAIL"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "email");

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.COMPANY_NM</code>. 회사명
     */
    public final TableField<TbAdminContactRecord, String> COMPANY_NM = createField(DSL.name("COMPANY_NM"), org.jooq.impl.SQLDataType.VARCHAR(200).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "회사명");

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.SUBJECT</code>. 문의 제목
     */
    public final TableField<TbAdminContactRecord, String> SUBJECT = createField(DSL.name("SUBJECT"), org.jooq.impl.SQLDataType.VARCHAR(1000).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "문의 제목");

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.MESSAGE</code>. 문의 본문
     */
    public final TableField<TbAdminContactRecord, String> MESSAGE = createField(DSL.name("MESSAGE"), org.jooq.impl.SQLDataType.VARCHAR(4000).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "문의 본문");

    /**
     * The column <code>rocketmart.TB_ADMIN_CONTACT.REG_TS</code>. 등록일시
     */
    public final TableField<TbAdminContactRecord, Timestamp> REG_TS = createField(DSL.name("REG_TS"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "등록일시");

    /**
     * Create a <code>rocketmart.TB_ADMIN_CONTACT</code> table reference
     */
    public TbAdminContact() {
        this(DSL.name("TB_ADMIN_CONTACT"), null);
    }

    /**
     * Create an aliased <code>rocketmart.TB_ADMIN_CONTACT</code> table reference
     */
    public TbAdminContact(String alias) {
        this(DSL.name(alias), TB_ADMIN_CONTACT);
    }

    /**
     * Create an aliased <code>rocketmart.TB_ADMIN_CONTACT</code> table reference
     */
    public TbAdminContact(Name alias) {
        this(alias, TB_ADMIN_CONTACT);
    }

    private TbAdminContact(Name alias, Table<TbAdminContactRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbAdminContact(Name alias, Table<TbAdminContactRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("관리자 문의"));
    }

    public <O extends Record> TbAdminContact(Table<O> child, ForeignKey<O, TbAdminContactRecord> key) {
        super(child, key, TB_ADMIN_CONTACT);
    }

    @Override
    public Schema getSchema() {
        return Rocketmart.ROCKETMART;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_ADMIN_CONTACT_PRIMARY);
    }

    @Override
    public UniqueKey<TbAdminContactRecord> getPrimaryKey() {
        return Keys.KEY_TB_ADMIN_CONTACT_PRIMARY;
    }

    @Override
    public List<UniqueKey<TbAdminContactRecord>> getKeys() {
        return Arrays.<UniqueKey<TbAdminContactRecord>>asList(Keys.KEY_TB_ADMIN_CONTACT_PRIMARY);
    }

    @Override
    public TbAdminContact as(String alias) {
        return new TbAdminContact(DSL.name(alias), this);
    }

    @Override
    public TbAdminContact as(Name alias) {
        return new TbAdminContact(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbAdminContact rename(String name) {
        return new TbAdminContact(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbAdminContact rename(Name name) {
        return new TbAdminContact(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
