/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables;


import com.rocketmart.jooq.Indexes;
import com.rocketmart.jooq.Keys;
import com.rocketmart.jooq.Rocketmart;
import com.rocketmart.jooq.tables.records.TbBrandMstRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 브랜드_정보
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbBrandMst extends TableImpl<TbBrandMstRecord> {

    private static final long serialVersionUID = 2035714718;

    /**
     * The reference instance of <code>rocketmart.tb_brand_mst</code>
     */
    public static final TbBrandMst TB_BRAND_MST = new TbBrandMst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbBrandMstRecord> getRecordType() {
        return TbBrandMstRecord.class;
    }

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_SEQ</code>.
     */
    public final TableField<TbBrandMstRecord, Long> BRAND_SEQ = createField(DSL.name("BRAND_SEQ"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_NM</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_NM = createField(DSL.name("BRAND_NM"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_LOGO</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_LOGO = createField(DSL.name("BRAND_LOGO"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_OWNERSHIP</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_OWNERSHIP = createField(DSL.name("BRAND_OWNERSHIP"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_HOMEPAGE_URL</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_HOMEPAGE_URL = createField(DSL.name("BRAND_HOMEPAGE_URL"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_YOUTUBE_URL</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_YOUTUBE_URL = createField(DSL.name("BRAND_YOUTUBE_URL"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_INSTAGRAM_URL</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_INSTAGRAM_URL = createField(DSL.name("BRAND_INSTAGRAM_URL"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_CERIFY</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_CERIFY = createField(DSL.name("BRAND_CERIFY"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>rocketmart.tb_brand_mst.BRAND_INTRODUCTION</code>.
     */
    public final TableField<TbBrandMstRecord, String> BRAND_INTRODUCTION = createField(DSL.name("BRAND_INTRODUCTION"), org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * Create a <code>rocketmart.tb_brand_mst</code> table reference
     */
    public TbBrandMst() {
        this(DSL.name("tb_brand_mst"), null);
    }

    /**
     * Create an aliased <code>rocketmart.tb_brand_mst</code> table reference
     */
    public TbBrandMst(String alias) {
        this(DSL.name(alias), TB_BRAND_MST);
    }

    /**
     * Create an aliased <code>rocketmart.tb_brand_mst</code> table reference
     */
    public TbBrandMst(Name alias) {
        this(alias, TB_BRAND_MST);
    }

    private TbBrandMst(Name alias, Table<TbBrandMstRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbBrandMst(Name alias, Table<TbBrandMstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("브랜드_정보"));
    }

    public <O extends Record> TbBrandMst(Table<O> child, ForeignKey<O, TbBrandMstRecord> key) {
        super(child, key, TB_BRAND_MST);
    }

    @Override
    public Schema getSchema() {
        return Rocketmart.ROCKETMART;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_BRAND_MST_PRIMARY);
    }

    @Override
    public Identity<TbBrandMstRecord, Long> getIdentity() {
        return Keys.IDENTITY_TB_BRAND_MST;
    }

    @Override
    public UniqueKey<TbBrandMstRecord> getPrimaryKey() {
        return Keys.KEY_TB_BRAND_MST_PRIMARY;
    }

    @Override
    public List<UniqueKey<TbBrandMstRecord>> getKeys() {
        return Arrays.<UniqueKey<TbBrandMstRecord>>asList(Keys.KEY_TB_BRAND_MST_PRIMARY);
    }

    @Override
    public TbBrandMst as(String alias) {
        return new TbBrandMst(DSL.name(alias), this);
    }

    @Override
    public TbBrandMst as(Name alias) {
        return new TbBrandMst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBrandMst rename(String name) {
        return new TbBrandMst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbBrandMst rename(Name name) {
        return new TbBrandMst(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
