/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables;


import com.rocketmart.jooq.Indexes;
import com.rocketmart.jooq.Keys;
import com.rocketmart.jooq.Rocketmart;
import com.rocketmart.jooq.tables.records.TbInquiryMstRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 상품 문의내역
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbInquiryMst extends TableImpl<TbInquiryMstRecord> {

    private static final long serialVersionUID = 1194892239;

    /**
     * The reference instance of <code>rocketmart.tb_inquiry_mst</code>
     */
    public static final TbInquiryMst TB_INQUIRY_MST = new TbInquiryMst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbInquiryMstRecord> getRecordType() {
        return TbInquiryMstRecord.class;
    }

    /**
     * The column <code>rocketmart.tb_inquiry_mst.INQUIRY_SEQ</code>. 상품문의 일련번호
     */
    public final TableField<TbInquiryMstRecord, Integer> INQUIRY_SEQ = createField(DSL.name("INQUIRY_SEQ"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "상품문의 일련번호");

    /**
     * The column <code>rocketmart.tb_inquiry_mst.MESSAGE</code>. 문의 내용
     */
    public final TableField<TbInquiryMstRecord, String> MESSAGE = createField(DSL.name("MESSAGE"), org.jooq.impl.SQLDataType.VARCHAR(4000).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "문의 내용");

    /**
     * The column <code>rocketmart.tb_inquiry_mst.REG_USR_ID</code>. 등록자아이디
     */
    public final TableField<TbInquiryMstRecord, String> REG_USR_ID = createField(DSL.name("REG_USR_ID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "등록자아이디");

    /**
     * The column <code>rocketmart.tb_inquiry_mst.REG_TS</code>. 등록일시
     */
    public final TableField<TbInquiryMstRecord, Timestamp> REG_TS = createField(DSL.name("REG_TS"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "등록일시");

    /**
     * The column <code>rocketmart.tb_inquiry_mst.UPD_USR_ID</code>. 수정자아이디
     */
    public final TableField<TbInquiryMstRecord, String> UPD_USR_ID = createField(DSL.name("UPD_USR_ID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "수정자아이디");

    /**
     * The column <code>rocketmart.tb_inquiry_mst.UPD_TS</code>. 수정일시
     */
    public final TableField<TbInquiryMstRecord, Timestamp> UPD_TS = createField(DSL.name("UPD_TS"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "수정일시");

    /**
     * Create a <code>rocketmart.tb_inquiry_mst</code> table reference
     */
    public TbInquiryMst() {
        this(DSL.name("tb_inquiry_mst"), null);
    }

    /**
     * Create an aliased <code>rocketmart.tb_inquiry_mst</code> table reference
     */
    public TbInquiryMst(String alias) {
        this(DSL.name(alias), TB_INQUIRY_MST);
    }

    /**
     * Create an aliased <code>rocketmart.tb_inquiry_mst</code> table reference
     */
    public TbInquiryMst(Name alias) {
        this(alias, TB_INQUIRY_MST);
    }

    private TbInquiryMst(Name alias, Table<TbInquiryMstRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbInquiryMst(Name alias, Table<TbInquiryMstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("상품 문의내역"));
    }

    public <O extends Record> TbInquiryMst(Table<O> child, ForeignKey<O, TbInquiryMstRecord> key) {
        super(child, key, TB_INQUIRY_MST);
    }

    @Override
    public Schema getSchema() {
        return Rocketmart.ROCKETMART;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_INQUIRY_MST_PRIMARY, Indexes.TB_INQUIRY_MST_TB_INQUIRY_MST_INQUIRY_SEQ_UINDEX);
    }

    @Override
    public Identity<TbInquiryMstRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TB_INQUIRY_MST;
    }

    @Override
    public UniqueKey<TbInquiryMstRecord> getPrimaryKey() {
        return Keys.KEY_TB_INQUIRY_MST_PRIMARY;
    }

    @Override
    public List<UniqueKey<TbInquiryMstRecord>> getKeys() {
        return Arrays.<UniqueKey<TbInquiryMstRecord>>asList(Keys.KEY_TB_INQUIRY_MST_PRIMARY, Keys.KEY_TB_INQUIRY_MST_TB_INQUIRY_MST_INQUIRY_SEQ_UINDEX);
    }

    @Override
    public TbInquiryMst as(String alias) {
        return new TbInquiryMst(DSL.name(alias), this);
    }

    @Override
    public TbInquiryMst as(Name alias) {
        return new TbInquiryMst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbInquiryMst rename(String name) {
        return new TbInquiryMst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbInquiryMst rename(Name name) {
        return new TbInquiryMst(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
