/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables;


import com.rocketmart.jooq.Indexes;
import com.rocketmart.jooq.Keys;
import com.rocketmart.jooq.Rocketmart;
import com.rocketmart.jooq.tables.records.TbPrdFobHstRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 사용자 FOB 가격 조회 이력
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbPrdFobHst extends TableImpl<TbPrdFobHstRecord> {

    private static final long serialVersionUID = 926524791;

    /**
     * The reference instance of <code>rocketmart.tb_prd_fob_hst</code>
     */
    public static final TbPrdFobHst TB_PRD_FOB_HST = new TbPrdFobHst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbPrdFobHstRecord> getRecordType() {
        return TbPrdFobHstRecord.class;
    }

    /**
     * The column <code>rocketmart.tb_prd_fob_hst.FOB_HST_SEQ</code>. FOB 조회 일련번호
     */
    public final TableField<TbPrdFobHstRecord, Integer> FOB_HST_SEQ = createField(DSL.name("FOB_HST_SEQ"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "FOB 조회 일련번호");

    /**
     * The column <code>rocketmart.tb_prd_fob_hst.PRODUCT_SEQ</code>. 상품 일련번호
     */
    public final TableField<TbPrdFobHstRecord, Integer> PRODUCT_SEQ = createField(DSL.name("PRODUCT_SEQ"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "상품 일련번호");

    /**
     * The column <code>rocketmart.tb_prd_fob_hst.REG_USR_ID</code>. 등록자 아이디
     */
    public final TableField<TbPrdFobHstRecord, String> REG_USR_ID = createField(DSL.name("REG_USR_ID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "등록자 아이디");

    /**
     * The column <code>rocketmart.tb_prd_fob_hst.REG_TS</code>. 등록일시
     */
    public final TableField<TbPrdFobHstRecord, Timestamp> REG_TS = createField(DSL.name("REG_TS"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "등록일시");

    /**
     * The column <code>rocketmart.tb_prd_fob_hst.UPD_USR_ID</code>. 수정자 아이디
     */
    public final TableField<TbPrdFobHstRecord, String> UPD_USR_ID = createField(DSL.name("UPD_USR_ID"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "수정자 아이디");

    /**
     * The column <code>rocketmart.tb_prd_fob_hst.UPD_TS</code>. 수정일시
     */
    public final TableField<TbPrdFobHstRecord, Timestamp> UPD_TS = createField(DSL.name("UPD_TS"), org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "수정일시");

    /**
     * Create a <code>rocketmart.tb_prd_fob_hst</code> table reference
     */
    public TbPrdFobHst() {
        this(DSL.name("tb_prd_fob_hst"), null);
    }

    /**
     * Create an aliased <code>rocketmart.tb_prd_fob_hst</code> table reference
     */
    public TbPrdFobHst(String alias) {
        this(DSL.name(alias), TB_PRD_FOB_HST);
    }

    /**
     * Create an aliased <code>rocketmart.tb_prd_fob_hst</code> table reference
     */
    public TbPrdFobHst(Name alias) {
        this(alias, TB_PRD_FOB_HST);
    }

    private TbPrdFobHst(Name alias, Table<TbPrdFobHstRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbPrdFobHst(Name alias, Table<TbPrdFobHstRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("사용자 FOB 가격 조회 이력"));
    }

    public <O extends Record> TbPrdFobHst(Table<O> child, ForeignKey<O, TbPrdFobHstRecord> key) {
        super(child, key, TB_PRD_FOB_HST);
    }

    @Override
    public Schema getSchema() {
        return Rocketmart.ROCKETMART;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_PRD_FOB_HST_PRIMARY, Indexes.TB_PRD_FOB_HST_TB_PRD_FOB_HST_TB_PRD_MST_PRODUCT_SEQ_FK);
    }

    @Override
    public Identity<TbPrdFobHstRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TB_PRD_FOB_HST;
    }

    @Override
    public UniqueKey<TbPrdFobHstRecord> getPrimaryKey() {
        return Keys.KEY_TB_PRD_FOB_HST_PRIMARY;
    }

    @Override
    public List<UniqueKey<TbPrdFobHstRecord>> getKeys() {
        return Arrays.<UniqueKey<TbPrdFobHstRecord>>asList(Keys.KEY_TB_PRD_FOB_HST_PRIMARY);
    }

    @Override
    public List<ForeignKey<TbPrdFobHstRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TbPrdFobHstRecord, ?>>asList(Keys.TB_PRD_FOB_HST_TB_PRD_MST_PRODUCT_SEQ_FK);
    }

    public TbPrdMst tbPrdMst() {
        return new TbPrdMst(this, Keys.TB_PRD_FOB_HST_TB_PRD_MST_PRODUCT_SEQ_FK);
    }

    @Override
    public TbPrdFobHst as(String alias) {
        return new TbPrdFobHst(DSL.name(alias), this);
    }

    @Override
    public TbPrdFobHst as(Name alias) {
        return new TbPrdFobHst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbPrdFobHst rename(String name) {
        return new TbPrdFobHst(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbPrdFobHst rename(Name name) {
        return new TbPrdFobHst(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
