/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables;


import com.rocketmart.jooq.Indexes;
import com.rocketmart.jooq.Keys;
import com.rocketmart.jooq.Rocketmart;
import com.rocketmart.jooq.tables.records.TbPrdFobRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 상품별 도매가격(FOB)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbPrdFob extends TableImpl<TbPrdFobRecord> {

    private static final long serialVersionUID = 437336626;

    /**
     * The reference instance of <code>rocketmart.TB_PRD_FOB</code>
     */
    public static final TbPrdFob TB_PRD_FOB = new TbPrdFob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbPrdFobRecord> getRecordType() {
        return TbPrdFobRecord.class;
    }

    /**
     * The column <code>rocketmart.TB_PRD_FOB.FOB_SEQ</code>. 도매가격(FOB) 일련번호
     */
    public final TableField<TbPrdFobRecord, Integer> FOB_SEQ = createField(DSL.name("FOB_SEQ"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "도매가격(FOB) 일련번호");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.PRODUCT_SEQ</code>. 상품 일련번호
     */
    public final TableField<TbPrdFobRecord, Integer> PRODUCT_SEQ = createField(DSL.name("PRODUCT_SEQ"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "상품 일련번호");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.RANGE_START</code>. 범위 구간 시작
     */
    public final TableField<TbPrdFobRecord, Long> RANGE_START = createField(DSL.name("RANGE_START"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "범위 구간 시작");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.RANGE_END</code>. 범위 구간 끝
     */
    public final TableField<TbPrdFobRecord, Long> RANGE_END = createField(DSL.name("RANGE_END"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "범위 구간 끝");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.TRADING_PRICE</code>. 거래가(U$)
     */
    public final TableField<TbPrdFobRecord, Long> TRADING_PRICE = createField(DSL.name("TRADING_PRICE"), org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.BIGINT)), this, "거래가(U$)");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.SUPPLY_RATE</code>. 공급률
     */
    public final TableField<TbPrdFobRecord, Integer> SUPPLY_RATE = createField(DSL.name("SUPPLY_RATE"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "공급률");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.OPTION_1</code>. 옵션1
     */
    public final TableField<TbPrdFobRecord, String> OPTION_1 = createField(DSL.name("OPTION_1"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "옵션1");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.OPTION_2</code>. 옵션2
     */
    public final TableField<TbPrdFobRecord, String> OPTION_2 = createField(DSL.name("OPTION_2"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "옵션2");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.OPTION_3</code>. 옵션3
     */
    public final TableField<TbPrdFobRecord, String> OPTION_3 = createField(DSL.name("OPTION_3"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "옵션3");

    /**
     * The column <code>rocketmart.TB_PRD_FOB.DEL_YN</code>. 삭제여부
     */
    public final TableField<TbPrdFobRecord, String> DEL_YN = createField(DSL.name("DEL_YN"), org.jooq.impl.SQLDataType.CHAR(1).defaultValue(org.jooq.impl.DSL.field("'N'", org.jooq.impl.SQLDataType.CHAR)), this, "삭제여부");

    /**
     * Create a <code>rocketmart.TB_PRD_FOB</code> table reference
     */
    public TbPrdFob() {
        this(DSL.name("TB_PRD_FOB"), null);
    }

    /**
     * Create an aliased <code>rocketmart.TB_PRD_FOB</code> table reference
     */
    public TbPrdFob(String alias) {
        this(DSL.name(alias), TB_PRD_FOB);
    }

    /**
     * Create an aliased <code>rocketmart.TB_PRD_FOB</code> table reference
     */
    public TbPrdFob(Name alias) {
        this(alias, TB_PRD_FOB);
    }

    private TbPrdFob(Name alias, Table<TbPrdFobRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbPrdFob(Name alias, Table<TbPrdFobRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("상품별 도매가격(FOB)"));
    }

    public <O extends Record> TbPrdFob(Table<O> child, ForeignKey<O, TbPrdFobRecord> key) {
        super(child, key, TB_PRD_FOB);
    }

    @Override
    public Schema getSchema() {
        return Rocketmart.ROCKETMART;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TB_PRD_FOB_PRIMARY, Indexes.TB_PRD_FOB_TB_PRD_FOB_TB_PRD_MST_PRODUCT_SEQ_FK);
    }

    @Override
    public Identity<TbPrdFobRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TB_PRD_FOB;
    }

    @Override
    public UniqueKey<TbPrdFobRecord> getPrimaryKey() {
        return Keys.KEY_TB_PRD_FOB_PRIMARY;
    }

    @Override
    public List<UniqueKey<TbPrdFobRecord>> getKeys() {
        return Arrays.<UniqueKey<TbPrdFobRecord>>asList(Keys.KEY_TB_PRD_FOB_PRIMARY);
    }

    @Override
    public List<ForeignKey<TbPrdFobRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TbPrdFobRecord, ?>>asList(Keys.TB_PRD_FOB_TB_PRD_MST_PRODUCT_SEQ_FK);
    }

    public TbPrdMst tbPrdMst() {
        return new TbPrdMst(this, Keys.TB_PRD_FOB_TB_PRD_MST_PRODUCT_SEQ_FK);
    }

    @Override
    public TbPrdFob as(String alias) {
        return new TbPrdFob(DSL.name(alias), this);
    }

    @Override
    public TbPrdFob as(Name alias) {
        return new TbPrdFob(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TbPrdFob rename(String name) {
        return new TbPrdFob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TbPrdFob rename(Name name) {
        return new TbPrdFob(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Long, Long, Long, Integer, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
