spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rocket2019!
    url: jdbc:mariadb://49.50.167.112:3306/rocketmart
    hikari:
      maximum-pool-size: 10

  jooq:
    sql-dialect: mariadb

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

afile:
  host: "http://localhost:8080"
  path: "C:\\rocketmart-pcweb\\src\\main\\resources\\static\\afiles\\"

logging:
  level:
    org.jooq.tools.LoggerListener: debug

server:
  port: 8080
  max-http-header-size: 1MB
