spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rocket2020!
    url: jdbc:mariadb://18.138.83.79:3306/rocketmart
    hikari:
      maximum-pool-size: 10

  jooq:
    sql-dialect: mariadb

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

afile:
  host: "http://18.138.83.79:8080"
  path: "C:/Program Files/Apache Software Foundation/Tomcat 8.5/webapps/ROOT/WEB-INF/classes/static/afiles/"

logging:
  level:
    org.jooq.tools.LoggerListener: debug

server:
  port: 80
  max-http-header-size: 1MB
