spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:qsvc.splite3
  jooq:
    sql-dialect: sqlite