spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb:http://127.0.0.1:3306/rocketmart
    hikari:
      maximum-pool-size: 10

  jooq:
    sql-dialect: mariadb

logging:
  level:
    org.jooq.tools.LoggerListener: debug
