/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables.records;


import com.rocketmart.jooq.tables.TbBrandMst;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 브랜드_정보
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbBrandMstRecord extends UpdatableRecordImpl<TbBrandMstRecord> implements Record9<Long, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -569862657;

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_SEQ</code>.
     */
    public void setBrandSeq(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_SEQ</code>.
     */
    public Long getBrandSeq() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_NM</code>.
     */
    public void setBrandNm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_NM</code>.
     */
    public String getBrandNm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_LOGO</code>.
     */
    public void setBrandLogo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_LOGO</code>.
     */
    public String getBrandLogo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_OWNERSHIP</code>.
     */
    public void setBrandOwnership(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_OWNERSHIP</code>.
     */
    public String getBrandOwnership() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_HOMEPAGE_URL</code>.
     */
    public void setBrandHomepageUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_HOMEPAGE_URL</code>.
     */
    public String getBrandHomepageUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_YOUTUBE_URL</code>.
     */
    public void setBrandYoutubeUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_YOUTUBE_URL</code>.
     */
    public String getBrandYoutubeUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_INSTAGRAM_URL</code>.
     */
    public void setBrandInstagramUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_INSTAGRAM_URL</code>.
     */
    public String getBrandInstagramUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_CERIFY</code>.
     */
    public void setBrandCerify(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_CERIFY</code>.
     */
    public String getBrandCerify() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rocketmart.tb_brand_mst.BRAND_INTRODUCTION</code>.
     */
    public void setBrandIntroduction(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>rocketmart.tb_brand_mst.BRAND_INTRODUCTION</code>.
     */
    public String getBrandIntroduction() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TbBrandMst.TB_BRAND_MST.BRAND_SEQ;
    }

    @Override
    public Field<String> field2() {
        return TbBrandMst.TB_BRAND_MST.BRAND_NM;
    }

    @Override
    public Field<String> field3() {
        return TbBrandMst.TB_BRAND_MST.BRAND_LOGO;
    }

    @Override
    public Field<String> field4() {
        return TbBrandMst.TB_BRAND_MST.BRAND_OWNERSHIP;
    }

    @Override
    public Field<String> field5() {
        return TbBrandMst.TB_BRAND_MST.BRAND_HOMEPAGE_URL;
    }

    @Override
    public Field<String> field6() {
        return TbBrandMst.TB_BRAND_MST.BRAND_YOUTUBE_URL;
    }

    @Override
    public Field<String> field7() {
        return TbBrandMst.TB_BRAND_MST.BRAND_INSTAGRAM_URL;
    }

    @Override
    public Field<String> field8() {
        return TbBrandMst.TB_BRAND_MST.BRAND_CERIFY;
    }

    @Override
    public Field<String> field9() {
        return TbBrandMst.TB_BRAND_MST.BRAND_INTRODUCTION;
    }

    @Override
    public Long component1() {
        return getBrandSeq();
    }

    @Override
    public String component2() {
        return getBrandNm();
    }

    @Override
    public String component3() {
        return getBrandLogo();
    }

    @Override
    public String component4() {
        return getBrandOwnership();
    }

    @Override
    public String component5() {
        return getBrandHomepageUrl();
    }

    @Override
    public String component6() {
        return getBrandYoutubeUrl();
    }

    @Override
    public String component7() {
        return getBrandInstagramUrl();
    }

    @Override
    public String component8() {
        return getBrandCerify();
    }

    @Override
    public String component9() {
        return getBrandIntroduction();
    }

    @Override
    public Long value1() {
        return getBrandSeq();
    }

    @Override
    public String value2() {
        return getBrandNm();
    }

    @Override
    public String value3() {
        return getBrandLogo();
    }

    @Override
    public String value4() {
        return getBrandOwnership();
    }

    @Override
    public String value5() {
        return getBrandHomepageUrl();
    }

    @Override
    public String value6() {
        return getBrandYoutubeUrl();
    }

    @Override
    public String value7() {
        return getBrandInstagramUrl();
    }

    @Override
    public String value8() {
        return getBrandCerify();
    }

    @Override
    public String value9() {
        return getBrandIntroduction();
    }

    @Override
    public TbBrandMstRecord value1(Long value) {
        setBrandSeq(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value2(String value) {
        setBrandNm(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value3(String value) {
        setBrandLogo(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value4(String value) {
        setBrandOwnership(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value5(String value) {
        setBrandHomepageUrl(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value6(String value) {
        setBrandYoutubeUrl(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value7(String value) {
        setBrandInstagramUrl(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value8(String value) {
        setBrandCerify(value);
        return this;
    }

    @Override
    public TbBrandMstRecord value9(String value) {
        setBrandIntroduction(value);
        return this;
    }

    @Override
    public TbBrandMstRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbBrandMstRecord
     */
    public TbBrandMstRecord() {
        super(TbBrandMst.TB_BRAND_MST);
    }

    /**
     * Create a detached, initialised TbBrandMstRecord
     */
    public TbBrandMstRecord(Long brandSeq, String brandNm, String brandLogo, String brandOwnership, String brandHomepageUrl, String brandYoutubeUrl, String brandInstagramUrl, String brandCerify, String brandIntroduction) {
        super(TbBrandMst.TB_BRAND_MST);

        set(0, brandSeq);
        set(1, brandNm);
        set(2, brandLogo);
        set(3, brandOwnership);
        set(4, brandHomepageUrl);
        set(5, brandYoutubeUrl);
        set(6, brandInstagramUrl);
        set(7, brandCerify);
        set(8, brandIntroduction);
    }
}
