/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables.records;


import com.rocketmart.jooq.tables.TbCmAfile;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record2;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 첨부파일
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCmAfileRecord extends UpdatableRecordImpl<TbCmAfileRecord> implements Record15<Integer, Integer, String, String, String, String, String, Integer, String, String, String, String, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = 1023789435;

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.AFILE_SEQ</code>. 첨부파일 일련번호
     */
    public void setAfileSeq(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.AFILE_SEQ</code>. 첨부파일 일련번호
     */
    public Integer getAfileSeq() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.AFILE_NO</code>. 첨부파일 순번
     */
    public void setAfileNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.AFILE_NO</code>. 첨부파일 순번
     */
    public Integer getAfileNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.ORGN_FILE_NM</code>. 원본 파일명
     */
    public void setOrgnFileNm(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.ORGN_FILE_NM</code>. 원본 파일명
     */
    public String getOrgnFileNm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.URL_PATH_CD</code>. URL 경로 코드
     */
    public void setUrlPathCd(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.URL_PATH_CD</code>. URL 경로 코드
     */
    public String getUrlPathCd() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.AFILE_PATH</code>. 첨부파일 경로
     */
    public void setAfilePath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.AFILE_PATH</code>. 첨부파일 경로
     */
    public String getAfilePath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.REG_FILE_NM</code>. 등록 파일명
     */
    public void setRegFileNm(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.REG_FILE_NM</code>. 등록 파일명
     */
    public String getRegFileNm() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.EXT</code>. 확장자명
     */
    public void setExt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.EXT</code>. 확장자명
     */
    public String getExt() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.AFILE_SIZE</code>. 첨부파일 사이즈
     */
    public void setAfileSize(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.AFILE_SIZE</code>. 첨부파일 사이즈
     */
    public Integer getAfileSize() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.THEMA_RELM_CD</code>. 영역 코드
     */
    public void setThemaRelmCd(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.THEMA_RELM_CD</code>. 영역 코드
     */
    public String getThemaRelmCd() {
        return (String) get(8);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.REG_MENU_PART</code>. 등록 메뉴 경로
     */
    public void setRegMenuPart(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.REG_MENU_PART</code>. 등록 메뉴 경로
     */
    public String getRegMenuPart() {
        return (String) get(9);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.DEL_YN</code>. 삭제여부
     */
    public void setDelYn(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.DEL_YN</code>. 삭제여부
     */
    public String getDelYn() {
        return (String) get(10);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.REG_USR_ID</code>. 등록자ID
     */
    public void setRegUsrId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.REG_USR_ID</code>. 등록자ID
     */
    public String getRegUsrId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.REG_TS</code>. 등록일시
     */
    public void setRegTs(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.REG_TS</code>. 등록일시
     */
    public Timestamp getRegTs() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.UPD_USR_ID</code>. 수정자ID
     */
    public void setUpdUsrId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.UPD_USR_ID</code>. 수정자ID
     */
    public String getUpdUsrId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>rocketmart.TB_CM_AFILE.UPD_DT</code>. 수정일시
     */
    public void setUpdDt(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>rocketmart.TB_CM_AFILE.UPD_DT</code>. 수정일시
     */
    public Timestamp getUpdDt() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, Integer, String, String, String, String, String, Integer, String, String, String, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, Integer, String, String, String, String, String, Integer, String, String, String, String, Timestamp, String, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbCmAfile.TB_CM_AFILE.AFILE_SEQ;
    }

    @Override
    public Field<Integer> field2() {
        return TbCmAfile.TB_CM_AFILE.AFILE_NO;
    }

    @Override
    public Field<String> field3() {
        return TbCmAfile.TB_CM_AFILE.ORGN_FILE_NM;
    }

    @Override
    public Field<String> field4() {
        return TbCmAfile.TB_CM_AFILE.URL_PATH_CD;
    }

    @Override
    public Field<String> field5() {
        return TbCmAfile.TB_CM_AFILE.AFILE_PATH;
    }

    @Override
    public Field<String> field6() {
        return TbCmAfile.TB_CM_AFILE.REG_FILE_NM;
    }

    @Override
    public Field<String> field7() {
        return TbCmAfile.TB_CM_AFILE.EXT;
    }

    @Override
    public Field<Integer> field8() {
        return TbCmAfile.TB_CM_AFILE.AFILE_SIZE;
    }

    @Override
    public Field<String> field9() {
        return TbCmAfile.TB_CM_AFILE.THEMA_RELM_CD;
    }

    @Override
    public Field<String> field10() {
        return TbCmAfile.TB_CM_AFILE.REG_MENU_PART;
    }

    @Override
    public Field<String> field11() {
        return TbCmAfile.TB_CM_AFILE.DEL_YN;
    }

    @Override
    public Field<String> field12() {
        return TbCmAfile.TB_CM_AFILE.REG_USR_ID;
    }

    @Override
    public Field<Timestamp> field13() {
        return TbCmAfile.TB_CM_AFILE.REG_TS;
    }

    @Override
    public Field<String> field14() {
        return TbCmAfile.TB_CM_AFILE.UPD_USR_ID;
    }

    @Override
    public Field<Timestamp> field15() {
        return TbCmAfile.TB_CM_AFILE.UPD_DT;
    }

    @Override
    public Integer component1() {
        return getAfileSeq();
    }

    @Override
    public Integer component2() {
        return getAfileNo();
    }

    @Override
    public String component3() {
        return getOrgnFileNm();
    }

    @Override
    public String component4() {
        return getUrlPathCd();
    }

    @Override
    public String component5() {
        return getAfilePath();
    }

    @Override
    public String component6() {
        return getRegFileNm();
    }

    @Override
    public String component7() {
        return getExt();
    }

    @Override
    public Integer component8() {
        return getAfileSize();
    }

    @Override
    public String component9() {
        return getThemaRelmCd();
    }

    @Override
    public String component10() {
        return getRegMenuPart();
    }

    @Override
    public String component11() {
        return getDelYn();
    }

    @Override
    public String component12() {
        return getRegUsrId();
    }

    @Override
    public Timestamp component13() {
        return getRegTs();
    }

    @Override
    public String component14() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp component15() {
        return getUpdDt();
    }

    @Override
    public Integer value1() {
        return getAfileSeq();
    }

    @Override
    public Integer value2() {
        return getAfileNo();
    }

    @Override
    public String value3() {
        return getOrgnFileNm();
    }

    @Override
    public String value4() {
        return getUrlPathCd();
    }

    @Override
    public String value5() {
        return getAfilePath();
    }

    @Override
    public String value6() {
        return getRegFileNm();
    }

    @Override
    public String value7() {
        return getExt();
    }

    @Override
    public Integer value8() {
        return getAfileSize();
    }

    @Override
    public String value9() {
        return getThemaRelmCd();
    }

    @Override
    public String value10() {
        return getRegMenuPart();
    }

    @Override
    public String value11() {
        return getDelYn();
    }

    @Override
    public String value12() {
        return getRegUsrId();
    }

    @Override
    public Timestamp value13() {
        return getRegTs();
    }

    @Override
    public String value14() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp value15() {
        return getUpdDt();
    }

    @Override
    public TbCmAfileRecord value1(Integer value) {
        setAfileSeq(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value2(Integer value) {
        setAfileNo(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value3(String value) {
        setOrgnFileNm(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value4(String value) {
        setUrlPathCd(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value5(String value) {
        setAfilePath(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value6(String value) {
        setRegFileNm(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value7(String value) {
        setExt(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value8(Integer value) {
        setAfileSize(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value9(String value) {
        setThemaRelmCd(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value10(String value) {
        setRegMenuPart(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value11(String value) {
        setDelYn(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value12(String value) {
        setRegUsrId(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value13(Timestamp value) {
        setRegTs(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value14(String value) {
        setUpdUsrId(value);
        return this;
    }

    @Override
    public TbCmAfileRecord value15(Timestamp value) {
        setUpdDt(value);
        return this;
    }

    @Override
    public TbCmAfileRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, String value10, String value11, String value12, Timestamp value13, String value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCmAfileRecord
     */
    public TbCmAfileRecord() {
        super(TbCmAfile.TB_CM_AFILE);
    }

    /**
     * Create a detached, initialised TbCmAfileRecord
     */
    public TbCmAfileRecord(Integer afileSeq, Integer afileNo, String orgnFileNm, String urlPathCd, String afilePath, String regFileNm, String ext, Integer afileSize, String themaRelmCd, String regMenuPart, String delYn, String regUsrId, Timestamp regTs, String updUsrId, Timestamp updDt) {
        super(TbCmAfile.TB_CM_AFILE);

        set(0, afileSeq);
        set(1, afileNo);
        set(2, orgnFileNm);
        set(3, urlPathCd);
        set(4, afilePath);
        set(5, regFileNm);
        set(6, ext);
        set(7, afileSize);
        set(8, themaRelmCd);
        set(9, regMenuPart);
        set(10, delYn);
        set(11, regUsrId);
        set(12, regTs);
        set(13, updUsrId);
        set(14, updDt);
    }
}
