/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables.records;


import com.rocketmart.jooq.tables.TbInquiryMst;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 상품 문의내역
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbInquiryMstRecord extends UpdatableRecordImpl<TbInquiryMstRecord> implements Record6<Integer, String, String, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = -1508776332;

    /**
     * Setter for <code>rocketmart.tb_inquiry_mst.INQUIRY_SEQ</code>. 상품문의 일련번호
     */
    public void setInquirySeq(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rocketmart.tb_inquiry_mst.INQUIRY_SEQ</code>. 상품문의 일련번호
     */
    public Integer getInquirySeq() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rocketmart.tb_inquiry_mst.MESSAGE</code>. 문의 내용
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rocketmart.tb_inquiry_mst.MESSAGE</code>. 문의 내용
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rocketmart.tb_inquiry_mst.REG_USR_ID</code>. 등록자아이디
     */
    public void setRegUsrId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rocketmart.tb_inquiry_mst.REG_USR_ID</code>. 등록자아이디
     */
    public String getRegUsrId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rocketmart.tb_inquiry_mst.REG_TS</code>. 등록일시
     */
    public void setRegTs(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>rocketmart.tb_inquiry_mst.REG_TS</code>. 등록일시
     */
    public Timestamp getRegTs() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>rocketmart.tb_inquiry_mst.UPD_USR_ID</code>. 수정자아이디
     */
    public void setUpdUsrId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rocketmart.tb_inquiry_mst.UPD_USR_ID</code>. 수정자아이디
     */
    public String getUpdUsrId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rocketmart.tb_inquiry_mst.UPD_TS</code>. 수정일시
     */
    public void setUpdTs(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>rocketmart.tb_inquiry_mst.UPD_TS</code>. 수정일시
     */
    public Timestamp getUpdTs() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Timestamp, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbInquiryMst.TB_INQUIRY_MST.INQUIRY_SEQ;
    }

    @Override
    public Field<String> field2() {
        return TbInquiryMst.TB_INQUIRY_MST.MESSAGE;
    }

    @Override
    public Field<String> field3() {
        return TbInquiryMst.TB_INQUIRY_MST.REG_USR_ID;
    }

    @Override
    public Field<Timestamp> field4() {
        return TbInquiryMst.TB_INQUIRY_MST.REG_TS;
    }

    @Override
    public Field<String> field5() {
        return TbInquiryMst.TB_INQUIRY_MST.UPD_USR_ID;
    }

    @Override
    public Field<Timestamp> field6() {
        return TbInquiryMst.TB_INQUIRY_MST.UPD_TS;
    }

    @Override
    public Integer component1() {
        return getInquirySeq();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public String component3() {
        return getRegUsrId();
    }

    @Override
    public Timestamp component4() {
        return getRegTs();
    }

    @Override
    public String component5() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp component6() {
        return getUpdTs();
    }

    @Override
    public Integer value1() {
        return getInquirySeq();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public String value3() {
        return getRegUsrId();
    }

    @Override
    public Timestamp value4() {
        return getRegTs();
    }

    @Override
    public String value5() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp value6() {
        return getUpdTs();
    }

    @Override
    public TbInquiryMstRecord value1(Integer value) {
        setInquirySeq(value);
        return this;
    }

    @Override
    public TbInquiryMstRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public TbInquiryMstRecord value3(String value) {
        setRegUsrId(value);
        return this;
    }

    @Override
    public TbInquiryMstRecord value4(Timestamp value) {
        setRegTs(value);
        return this;
    }

    @Override
    public TbInquiryMstRecord value5(String value) {
        setUpdUsrId(value);
        return this;
    }

    @Override
    public TbInquiryMstRecord value6(Timestamp value) {
        setUpdTs(value);
        return this;
    }

    @Override
    public TbInquiryMstRecord values(Integer value1, String value2, String value3, Timestamp value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbInquiryMstRecord
     */
    public TbInquiryMstRecord() {
        super(TbInquiryMst.TB_INQUIRY_MST);
    }

    /**
     * Create a detached, initialised TbInquiryMstRecord
     */
    public TbInquiryMstRecord(Integer inquirySeq, String message, String regUsrId, Timestamp regTs, String updUsrId, Timestamp updTs) {
        super(TbInquiryMst.TB_INQUIRY_MST);

        set(0, inquirySeq);
        set(1, message);
        set(2, regUsrId);
        set(3, regTs);
        set(4, updUsrId);
        set(5, updTs);
    }
}
