/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables.records;


import com.rocketmart.jooq.tables.TbMemMst;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 회원정보 마스터
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbMemMstRecord extends UpdatableRecordImpl<TbMemMstRecord> implements Record13<Integer, String, String, String, String, String, String, String, Integer, String, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = -934054879;

    /**
     * Setter for <code>rocketmart.tb_mem_mst.MEM_SEQ</code>. 회원정보 일련번호
     */
    public void setMemSeq(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.MEM_SEQ</code>. 회원정보 일련번호
     */
    public Integer getMemSeq() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.ROLE</code>. 역할
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.ROLE</code>. 역할
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.MEM_ID</code>. 회원아이디(이메일)
     */
    public void setMemId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.MEM_ID</code>. 회원아이디(이메일)
     */
    public String getMemId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.MEM_NM</code>. 회원명
     */
    public void setMemNm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.MEM_NM</code>. 회원명
     */
    public String getMemNm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.MEM_PW</code>. 비밀번호
     */
    public void setMemPw(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.MEM_PW</code>. 비밀번호
     */
    public String getMemPw() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.TEL</code>. 전화번호
     */
    public void setTel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.TEL</code>. 전화번호
     */
    public String getTel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.COMPANY_NM</code>. 회사명
     */
    public void setCompanyNm(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.COMPANY_NM</code>. 회사명
     */
    public String getCompanyNm() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.COMPANY_URL</code>. 회사URL
     */
    public void setCompanyUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.COMPANY_URL</code>. 회사URL
     */
    public String getCompanyUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.BSNS_RGSTR_SEQ</code>. 사업자등록증 일련번호
     */
    public void setBsnsRgstrSeq(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.BSNS_RGSTR_SEQ</code>. 사업자등록증 일련번호
     */
    public Integer getBsnsRgstrSeq() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.REG_USR_ID</code>. 등록자 아이디
     */
    public void setRegUsrId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.REG_USR_ID</code>. 등록자 아이디
     */
    public String getRegUsrId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.REG_TS</code>. 등록일시
     */
    public void setRegTs(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.REG_TS</code>. 등록일시
     */
    public Timestamp getRegTs() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.UPD_USR_ID</code>. 수정자 아이디
     */
    public void setUpdUsrId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.UPD_USR_ID</code>. 수정자 아이디
     */
    public String getUpdUsrId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>rocketmart.tb_mem_mst.UPD_TS</code>. 수정일시
     */
    public void setUpdTs(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>rocketmart.tb_mem_mst.UPD_TS</code>. 수정일시
     */
    public Timestamp getUpdTs() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, String, String, String, String, String, String, String, Integer, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, String, String, String, String, String, String, String, Integer, String, Timestamp, String, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbMemMst.TB_MEM_MST.MEM_SEQ;
    }

    @Override
    public Field<String> field2() {
        return TbMemMst.TB_MEM_MST.ROLE;
    }

    @Override
    public Field<String> field3() {
        return TbMemMst.TB_MEM_MST.MEM_ID;
    }

    @Override
    public Field<String> field4() {
        return TbMemMst.TB_MEM_MST.MEM_NM;
    }

    @Override
    public Field<String> field5() {
        return TbMemMst.TB_MEM_MST.MEM_PW;
    }

    @Override
    public Field<String> field6() {
        return TbMemMst.TB_MEM_MST.TEL;
    }

    @Override
    public Field<String> field7() {
        return TbMemMst.TB_MEM_MST.COMPANY_NM;
    }

    @Override
    public Field<String> field8() {
        return TbMemMst.TB_MEM_MST.COMPANY_URL;
    }

    @Override
    public Field<Integer> field9() {
        return TbMemMst.TB_MEM_MST.BSNS_RGSTR_SEQ;
    }

    @Override
    public Field<String> field10() {
        return TbMemMst.TB_MEM_MST.REG_USR_ID;
    }

    @Override
    public Field<Timestamp> field11() {
        return TbMemMst.TB_MEM_MST.REG_TS;
    }

    @Override
    public Field<String> field12() {
        return TbMemMst.TB_MEM_MST.UPD_USR_ID;
    }

    @Override
    public Field<Timestamp> field13() {
        return TbMemMst.TB_MEM_MST.UPD_TS;
    }

    @Override
    public Integer component1() {
        return getMemSeq();
    }

    @Override
    public String component2() {
        return getRole();
    }

    @Override
    public String component3() {
        return getMemId();
    }

    @Override
    public String component4() {
        return getMemNm();
    }

    @Override
    public String component5() {
        return getMemPw();
    }

    @Override
    public String component6() {
        return getTel();
    }

    @Override
    public String component7() {
        return getCompanyNm();
    }

    @Override
    public String component8() {
        return getCompanyUrl();
    }

    @Override
    public Integer component9() {
        return getBsnsRgstrSeq();
    }

    @Override
    public String component10() {
        return getRegUsrId();
    }

    @Override
    public Timestamp component11() {
        return getRegTs();
    }

    @Override
    public String component12() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp component13() {
        return getUpdTs();
    }

    @Override
    public Integer value1() {
        return getMemSeq();
    }

    @Override
    public String value2() {
        return getRole();
    }

    @Override
    public String value3() {
        return getMemId();
    }

    @Override
    public String value4() {
        return getMemNm();
    }

    @Override
    public String value5() {
        return getMemPw();
    }

    @Override
    public String value6() {
        return getTel();
    }

    @Override
    public String value7() {
        return getCompanyNm();
    }

    @Override
    public String value8() {
        return getCompanyUrl();
    }

    @Override
    public Integer value9() {
        return getBsnsRgstrSeq();
    }

    @Override
    public String value10() {
        return getRegUsrId();
    }

    @Override
    public Timestamp value11() {
        return getRegTs();
    }

    @Override
    public String value12() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp value13() {
        return getUpdTs();
    }

    @Override
    public TbMemMstRecord value1(Integer value) {
        setMemSeq(value);
        return this;
    }

    @Override
    public TbMemMstRecord value2(String value) {
        setRole(value);
        return this;
    }

    @Override
    public TbMemMstRecord value3(String value) {
        setMemId(value);
        return this;
    }

    @Override
    public TbMemMstRecord value4(String value) {
        setMemNm(value);
        return this;
    }

    @Override
    public TbMemMstRecord value5(String value) {
        setMemPw(value);
        return this;
    }

    @Override
    public TbMemMstRecord value6(String value) {
        setTel(value);
        return this;
    }

    @Override
    public TbMemMstRecord value7(String value) {
        setCompanyNm(value);
        return this;
    }

    @Override
    public TbMemMstRecord value8(String value) {
        setCompanyUrl(value);
        return this;
    }

    @Override
    public TbMemMstRecord value9(Integer value) {
        setBsnsRgstrSeq(value);
        return this;
    }

    @Override
    public TbMemMstRecord value10(String value) {
        setRegUsrId(value);
        return this;
    }

    @Override
    public TbMemMstRecord value11(Timestamp value) {
        setRegTs(value);
        return this;
    }

    @Override
    public TbMemMstRecord value12(String value) {
        setUpdUsrId(value);
        return this;
    }

    @Override
    public TbMemMstRecord value13(Timestamp value) {
        setUpdTs(value);
        return this;
    }

    @Override
    public TbMemMstRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9, String value10, Timestamp value11, String value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbMemMstRecord
     */
    public TbMemMstRecord() {
        super(TbMemMst.TB_MEM_MST);
    }

    /**
     * Create a detached, initialised TbMemMstRecord
     */
    public TbMemMstRecord(Integer memSeq, String role, String memId, String memNm, String memPw, String tel, String companyNm, String companyUrl, Integer bsnsRgstrSeq, String regUsrId, Timestamp regTs, String updUsrId, Timestamp updTs) {
        super(TbMemMst.TB_MEM_MST);

        set(0, memSeq);
        set(1, role);
        set(2, memId);
        set(3, memNm);
        set(4, memPw);
        set(5, tel);
        set(6, companyNm);
        set(7, companyUrl);
        set(8, bsnsRgstrSeq);
        set(9, regUsrId);
        set(10, regTs);
        set(11, updUsrId);
        set(12, updTs);
    }
}
