/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq.tables.records;


import com.rocketmart.jooq.tables.TbWishMst;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * WISH LIST 마스터
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbWishMstRecord extends UpdatableRecordImpl<TbWishMstRecord> implements Record8<Integer, Integer, String, String, String, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = -657697246;

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.WISH_SEQ</code>. 위시 일련번호
     */
    public void setWishSeq(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.WISH_SEQ</code>. 위시 일련번호
     */
    public Integer getWishSeq() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.PRODUCT_SEQ</code>. 상품 일련번호
     */
    public void setProductSeq(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.PRODUCT_SEQ</code>. 상품 일련번호
     */
    public Integer getProductSeq() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.ASK_YN</code>. 문의여부
     */
    public void setAskYn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.ASK_YN</code>. 문의여부
     */
    public String getAskYn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.DEL_YN</code>. 삭제여부
     */
    public void setDelYn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.DEL_YN</code>. 삭제여부
     */
    public String getDelYn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.REG_USR_ID</code>. 등록자아이디
     */
    public void setRegUsrId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.REG_USR_ID</code>. 등록자아이디
     */
    public String getRegUsrId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.REG_TS</code>. 등록일시
     */
    public void setRegTs(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.REG_TS</code>. 등록일시
     */
    public Timestamp getRegTs() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.UPD_USR_ID</code>. 수정자아이디
     */
    public void setUpdUsrId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.UPD_USR_ID</code>. 수정자아이디
     */
    public String getUpdUsrId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>rocketmart.TB_WISH_MST.UPD_TS</code>. 수정일시
     */
    public void setUpdTs(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>rocketmart.TB_WISH_MST.UPD_TS</code>. 수정일시
     */
    public Timestamp getUpdTs() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, String, String, Timestamp, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, String, String, Timestamp, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TbWishMst.TB_WISH_MST.WISH_SEQ;
    }

    @Override
    public Field<Integer> field2() {
        return TbWishMst.TB_WISH_MST.PRODUCT_SEQ;
    }

    @Override
    public Field<String> field3() {
        return TbWishMst.TB_WISH_MST.ASK_YN;
    }

    @Override
    public Field<String> field4() {
        return TbWishMst.TB_WISH_MST.DEL_YN;
    }

    @Override
    public Field<String> field5() {
        return TbWishMst.TB_WISH_MST.REG_USR_ID;
    }

    @Override
    public Field<Timestamp> field6() {
        return TbWishMst.TB_WISH_MST.REG_TS;
    }

    @Override
    public Field<String> field7() {
        return TbWishMst.TB_WISH_MST.UPD_USR_ID;
    }

    @Override
    public Field<Timestamp> field8() {
        return TbWishMst.TB_WISH_MST.UPD_TS;
    }

    @Override
    public Integer component1() {
        return getWishSeq();
    }

    @Override
    public Integer component2() {
        return getProductSeq();
    }

    @Override
    public String component3() {
        return getAskYn();
    }

    @Override
    public String component4() {
        return getDelYn();
    }

    @Override
    public String component5() {
        return getRegUsrId();
    }

    @Override
    public Timestamp component6() {
        return getRegTs();
    }

    @Override
    public String component7() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp component8() {
        return getUpdTs();
    }

    @Override
    public Integer value1() {
        return getWishSeq();
    }

    @Override
    public Integer value2() {
        return getProductSeq();
    }

    @Override
    public String value3() {
        return getAskYn();
    }

    @Override
    public String value4() {
        return getDelYn();
    }

    @Override
    public String value5() {
        return getRegUsrId();
    }

    @Override
    public Timestamp value6() {
        return getRegTs();
    }

    @Override
    public String value7() {
        return getUpdUsrId();
    }

    @Override
    public Timestamp value8() {
        return getUpdTs();
    }

    @Override
    public TbWishMstRecord value1(Integer value) {
        setWishSeq(value);
        return this;
    }

    @Override
    public TbWishMstRecord value2(Integer value) {
        setProductSeq(value);
        return this;
    }

    @Override
    public TbWishMstRecord value3(String value) {
        setAskYn(value);
        return this;
    }

    @Override
    public TbWishMstRecord value4(String value) {
        setDelYn(value);
        return this;
    }

    @Override
    public TbWishMstRecord value5(String value) {
        setRegUsrId(value);
        return this;
    }

    @Override
    public TbWishMstRecord value6(Timestamp value) {
        setRegTs(value);
        return this;
    }

    @Override
    public TbWishMstRecord value7(String value) {
        setUpdUsrId(value);
        return this;
    }

    @Override
    public TbWishMstRecord value8(Timestamp value) {
        setUpdTs(value);
        return this;
    }

    @Override
    public TbWishMstRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Timestamp value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbWishMstRecord
     */
    public TbWishMstRecord() {
        super(TbWishMst.TB_WISH_MST);
    }

    /**
     * Create a detached, initialised TbWishMstRecord
     */
    public TbWishMstRecord(Integer wishSeq, Integer productSeq, String askYn, String delYn, String regUsrId, Timestamp regTs, String updUsrId, Timestamp updTs) {
        super(TbWishMst.TB_WISH_MST);

        set(0, wishSeq);
        set(1, productSeq);
        set(2, askYn);
        set(3, delYn);
        set(4, regUsrId);
        set(5, regTs);
        set(6, updUsrId);
        set(7, updTs);
    }
}
