/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq;


import com.rocketmart.jooq.tables.TbBrandMst;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in rocketmart
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 브랜드_정보
     */
    public static final TbBrandMst TB_BRAND_MST = TbBrandMst.TB_BRAND_MST;
}
