/*
 * This file is generated by jOOQ.
 */
package com.rocketmart.jooq;


import com.rocketmart.jooq.tables.TbBrandMst;
import com.rocketmart.jooq.tables.TbCateMst;
import com.rocketmart.jooq.tables.TbCmAfile;
import com.rocketmart.jooq.tables.TbContactUs;
import com.rocketmart.jooq.tables.TbInquiryDtl;
import com.rocketmart.jooq.tables.TbInquiryMst;
import com.rocketmart.jooq.tables.TbMemMst;
import com.rocketmart.jooq.tables.TbPrdFob;
import com.rocketmart.jooq.tables.TbPrdFobHst;
import com.rocketmart.jooq.tables.TbPrdMst;
import com.rocketmart.jooq.tables.TbWishMst;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in rocketmart
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 브랜드_정보
     */
    public static final TbBrandMst TB_BRAND_MST = TbBrandMst.TB_BRAND_MST;

    /**
     * 카테고리_정보
     */
    public static final TbCateMst TB_CATE_MST = TbCateMst.TB_CATE_MST;

    /**
     * 첨부파일
     */
    public static final TbCmAfile TB_CM_AFILE = TbCmAfile.TB_CM_AFILE;

    /**
     * 관리자 문의
     */
    public static final TbContactUs TB_CONTACT_US = TbContactUs.TB_CONTACT_US;

    /**
     * 상품 문의내역 상세
     */
    public static final TbInquiryDtl TB_INQUIRY_DTL = TbInquiryDtl.TB_INQUIRY_DTL;

    /**
     * 상품 문의내역
     */
    public static final TbInquiryMst TB_INQUIRY_MST = TbInquiryMst.TB_INQUIRY_MST;

    /**
     * 회원정보 마스터
     */
    public static final TbMemMst TB_MEM_MST = TbMemMst.TB_MEM_MST;

    /**
     * 상품별 도매가격(FOB)
     */
    public static final TbPrdFob TB_PRD_FOB = TbPrdFob.TB_PRD_FOB;

    /**
     * 사용자 FOB 가격 조회 이력
     */
    public static final TbPrdFobHst TB_PRD_FOB_HST = TbPrdFobHst.TB_PRD_FOB_HST;

    /**
     * 상품 마스터
     */
    public static final TbPrdMst TB_PRD_MST = TbPrdMst.TB_PRD_MST;

    /**
     * WISH LIST 마스터
     */
    public static final TbWishMst TB_WISH_MST = TbWishMst.TB_WISH_MST;
}
